inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - Gemfile
  Exclude:
    - db/schema.rb
    - config/initializers/devise.rb
Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

MethodLength:
  Exclude:
    - db/migrate/*.rb